### ISSUE TITLE
Stop pagination based on timestamp

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/gha-remove-artifacts#2]
Since artifacts are automatically cleaned up after 3 months, the pagination of workflow runs can be stopped after this timestamp is reached.

**Comment by gomorizsolt** [comment]
Turns out, we cannot rely on the optional additional function to filter the workflows older than 3 months.

> Note that you still have to return the value you want to map the response to, otherwise the last response will be mapped to undefined.

What this means is that it doesn't filter the elements from the pages if `done()` is called. It just stops the pagination, i.e. it doesn't go to the next page if it's called(that's why the doc doesn't return with `done()` either which was a bit interesting at first glance). Simply put, we have to filter the items here:

https://github.com/c-hive/gha-remove-artifacts/blob/ff173deac6af7d6013ca10a7f2270edc6ab0aa88/index.js#L74-L85

Instead of relying on the optional function.

**Comment by gomorizsolt** [comment]
> Since artifacts are automatically cleaned up after 3 months

I'd stress this point even if I'm nitpicking a bit. To be precise, it's [90 days](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-or-deleting-artifacts):

> Artifacts automatically expire after 90 days, but you can always reclaim used GitHub Actions storage by deleting artifacts before they expire on GitHub.

I mean 3 months is certainly longer than 90 days.

**Comment by thisismydesign** [comment]
Replying to https://github.com/c-hive/gha-remove-artifacts/issues/2#issuecomment-600038135:

The main point is to stop the pagination. If on the last page we have a few older items that's fine. It's just that we shouldn't paginate over years of workflows potentially. So I'd say this is not needed actually: https://github.com/c-hive/gha-remove-artifacts/pull/17/commits/11901639ed10b329972ba062e1de33d5176562d3
Let's just have the call of `done` instead.

**Comment by gomorizsolt** [comment]
Ah, gotcha, I'll adjust the changes accordingly.

**Comment by gomorizsolt** [comment]
Resolved by #17.
